name: Test

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ApeWorX/github-action@v1

    - name: Compile contracts
      run: ape compile --size

    - name: Run tests
      run: ape test -s
